language: node_js

node_js:
  - 12

cache:
  yarn: true

install:
  - yarn --frozen-lockfile

stages:
  - lint
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - yarn run test
    - stage: lint
      script:
        - yarn run lint
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
